### ISSUE TITLE
Criando portfólio do aluno 2

### ISSUE THREAD

**Issue by annabalves** [annabalves/ProjetoAvaliativo#4]

**Comment by BrunoDua** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="css/style.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfólio</title>
</head>
    <body> 
        <br><br><br><br><br>
            <h3>Sobre mim</h3>
            <p>
                Me chamo Bruno Duarte, tenho 26 anos. Tenho facilidade em trabalhar em equipe. Costumo me adaptar a <br> qualquer ambiente, 
                e procuro dar o melhor com intuito de enobrece o nome da empresa e o meu. A área que mais me chama <br> 
                atenção no ambiente da programação é a de banco de dados. 
            </p>
        
            <h3>Formação</h3>
            <p>
                  Graduação: Análise e Desenvolvimento de Sistemas - IESB
            </p>

            <h3>Hobbies</h3>
            <p>
                enho como hobby está próximo da família e amigos próximos, sair para ambientes mais light, ouvir músicas e participar de jogos em gerais.
            </p>
        
        <div class="h1">
            <h1>Bruno Duarte</h1>
        </div>
        <br><br><br>
        <div class="h2">        
            <h2>Arquiteto</h2>
        </div>
        <br><br><br>
    <header>
        <main>
            <a href= "#" target="_blank" rel="noopener noreferrer">
                <img src="img/githug.png">
                <p>GitHub</p>
            </a>
            <a href="#" target="_blank" rel="noopener noreferrer">
                <img src="img/linkedin.png">
                <p>Linkedin</p>
            </a>
        </main>
    </header>
    <br><br><br><br><br><br><br>
    <header>
        <footer>
            <img src= "img/bruno.jpeg">
        </footer>
    </header>
    </body>
</html>


body {
    color: black;
    background-color: rgb(248, 237, 248);
}

ul{
    display: none;
    justify-content: space-between;
    list-style-type: none;
    align-items: center;
    padding: 16px;
}

.h1 {
    position: fixed;
    left: 1010px;
    font-size: 19px;
    font-style: italic;
    top: 10px;
}

.h2 {
    position: fixed;
    left: 1060px;
    color: rgb(95, 95, 95);
    top: 55px;
}

main img {
    width: 30px;
    height: 30px;
}

main {
    display: flex;
    justify-content: center;
    position: fixed;
    left: 1029px;
    top: 110px;
}

main a {
    margin: 20px;
    text-align: center;
}

main p {
    margin-top: 2px;
}

footer img {
    width: 250px;
    height: 250px;
    border-radius: 50%;
    border: 2px solid #fff;
    position: fixed;
    left: 1000px;
    top: 220px;
}
