### ISSUE TITLE
Criando portfólio do aluno 3

### ISSUE THREAD

**Issue by annabalves** [annabalves/ProjetoAvaliativo#5]

**Comment by Rodrigo-Roger** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="css/style.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfólio</title>
</head>
    <body> 
        <br><br><br><br><br>
            <h3>Sobre mim</h3>
            <p>
                Me chamo Rodrigo Roger tenho 19 anos, um ótimo desenvolvedor, empenhado  em entregar qualquer demanda seja simples ou complexa, <br>
                não tenho problemas em trabalhar em equipe, sempre calmo para enteder meu papel em cada momento, agora estou a procura de uma 
                nova <br> experiência na área. Fique a vontade para dar uma olhada em alguns dos meus projetos disponíveis no Github e veja também 
                quem eu sou no <br>LinkedIn.
            </p>
        
            <h3>Formação</h3>
            <p>
                Ensino Médio Completo
                Graduação: Análise e Desenvolvimento de Sistemas - IESB
            </p>

            <h3>Hobbies</h3>
            <p>
                Gosto de ouvir música e ler.
            </p>
        
        <div class="h1">
            <h1>Rodrigo Roger</h1>
        </div>
        <br><br><br>
        <div class="h2">        
            <h2>Front end - Developer</h2>
        </div>
        <br><br><br>
    <header>
        <main>
            <a href= "https://github.com/Rodrigo-Roger" target="_blank" rel="noopener noreferrer">
                <img src="img/githug.png">
                <p>GitHub</p>
            </a>
            <a href="https://www.linkedin.com/in/rodrigo-roger-a39050235/" target="_blank" rel="noopener noreferrer">
                <img src="img/linkedin.png">
                <p>Linkedin</p>
            </a>
        </main>
    </header>
    <br><br><br><br><br><br><br>
    <header>
        <footer>
            <img src= "img/rodrigo2.jpeg">
        </footer>
    </header>
    </body>
</html>

**Comment by Rodrigo-Roger** [comment]
body {
    color: black;
    background-color: rgb(248, 237, 248);
}

ul{
    display: none;
    justify-content: space-between;
    list-style-type: none;
    align-items: center;
    padding: 16px;
}

.h1 {
    position: fixed;
    left: 1020px;
    font-size: 19px;
    font-style: italic;
    top: 10px;
}

.h2 {
    position: fixed;
    left: 1022px;
    color: rgb(95, 95, 95);
    top: 55px;
}

main img {
    width: 30px;
    height: 30px;
}

main {
    display: flex;
    justify-content: center;
    position: fixed;
    left: 1040px;
    top: 110px;
}

main a {
    margin: 20px;
    text-align: center;
}

main p {
    margin-top: 2px;
}

footer img {
    width: 250px;
    height: 250px;
    border-radius: 50%;
    border: 2px solid #fff;
    position: fixed;
    left: 1000px;
    top: 220px;
}
